name: Ambiente de testes - diadodiabetes.intest.com.br
on:
  push:
    branches:
      - develop
env:
  REGISTRY: "registry.digitalocean.com/intest"
  IMAGE_NAME: "diabetes-brasil-dia-do-diabetes"
  CONTAINER_CMD: "gatsby serve"

jobs:
  build:
    name: Obtém o código-fonte e realiza a construção da aplicação.
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Construindo imagem do projeto
        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$(echo $GITHUB_SHA | head -c7) .

      - name: Instalando o CLI da DigitalOcean
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Realizando login temporário no repositório de imagens
        run: doctl registry login --expiry-seconds 600

      - name: Envia a imagem para o repositório de imagens
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$(echo $GITHUB_SHA | head -c7)

  release:
    name: Acessa o servidor de testes e configura o container da aplicação
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Verifica o status do container existente
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_DEV_DEPLOY_HOST }}
          username: ${{ secrets.SSH_DEV_DEPLOY_USER }}
          key: ${{ secrets.SSH_DEV_DEPLOY_KEY }}
          port: 22
          script: |
            echo "Removendo container existente"
            docker rm -f diabetes-brasil-dia-do-diabetes

            echo "Criando novo container para a imagem ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$(echo $GITHUB_SHA | head -c7)"
            docker run -d -p 9000 \
              --name="diabetes-brasil-dia-do-diabetes" \
              --restart=unless-stopped \
              --volume=/mnt/intest-volume/diabetes-brasil-dia-do-diabetes/public:/app \
              -e VIRTUAL_PORT=9000 \
              -e VIRTUAL_HOST=diadodiabetes.intest.com.br \
              -e LETSENCRYPT_HOST=diadodiabetes.intest.com.br \
              -e LETSENCRYPT_EMAIL=dominios@studiovisual.com.br \
              --network webproxy \
             ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$(echo $GITHUB_SHA | head -c7) ${{ env.COMMAND }}

            echo "Reiniciando servidor de proxy"
            docker restart nginx-web nginx-gen

